"""
Question 2: Even Fibonacci Numbers
URL: https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

Measured Runtime: ~0.000009s
"""

import time


def solve(upper_limit: int = 4_000_000) -> int:
    even_fib_sum = 0

    a = 1
    b = 2

    while b <= upper_limit:
        if b % 2 == 0:
            even_fib_sum += b

        next_fib = a + b
        a = b
        b = next_fib

    return even_fib_sum


if __name__ == "__main__":
    start_time = time.perf_counter()
    answer = solve()
    elapsed = time.perf_counter() - start_time

    print(f"Answer: {answer}")
    print(f"Execution Time: {elapsed:.6f} seconds")
