"""
Question 12: Highly Divisible Triangular Number
URL: https://projecteuler.net/problem=12

The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.

The first ten terms would be:
1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?

Measured Runtime: ~0.044091s
"""

import time

def count_divisors(n: int) -> int:
    # Returns the total number of divisors for n using prime factorization
    divisors = 1
    d = 2
    while d * d <= n:
        if n % d == 0:
            exponent = 0
            while n % d == 0:
                exponent += 1
                n //= d
            divisors *= exponent + 1
        d += 1
    if n > 1:
        divisors *= 2  # Remaining prime factor raised to power 1
    return divisors


def solve(target_divisors: int = 500) -> int:
    n = 1
    while True:
        # Split n and n+1 since gcd(n, n+1) = 1
        a = n // 2 if n % 2 == 0 else n
        b = n + 1 if n % 2 == 0 else (n + 1) // 2

        total_divisors = count_divisors(a) * count_divisors(b)

        if total_divisors > target_divisors:
            triangle_number = n * (n + 1) // 2
            return triangle_number

        n += 1

if __name__ == "__main__":
    start_time = time.perf_counter()
    answer = solve()
    elapsed = time.perf_counter() - start_time

    print(f"Answer: {answer}")
    print(f"Execution Time: {elapsed:.6f} seconds")
