"""
Question 44: Pentagon Numbers
URL: https://projecteuler.net/problem=44

Pentagonal numbers are generated by the formula, P_n = n(3n - 1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P_4 + P_7 = 22 + 70 = 92 = P_8. However, their difference, 70 - 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, P_j and P_k, for which their sum and difference are pentagonal and
D = |P_k - P_j| is minimized; what is the value of D?

Measured Runtime: ~0.089792s
"""

import time


def is_pentagonal(n: int) -> bool:
    """Checks if a number is pentagonal."""
    if n <= 0:
        return False

    val = (1 + 24 * n) ** 0.5
    return val.is_integer() and (val + 1) % 6 == 0


def solve() -> int:
    """Finds the minimal difference D = |P_k - P_j| such that P_k + P_j and P_k - P_j are both pentagonal."""
    pent_set = set()
    pent_list = []
    k = 1

    while True:
        pk = k * (3 * k - 1) // 2
        for pj in reversed(pent_list):
            diff = pk - pj
            if diff in pent_set and is_pentagonal(pk + pj):
                return diff

        pent_set.add(pk)
        pent_list.append(pk)
        k += 1


if __name__ == "__main__":
    start_time = time.perf_counter()
    answer = solve()
    elapsed = time.perf_counter() - start_time

    print(f"Answer: {answer}")
    print(f"Execution Time: {elapsed:.6f} seconds")
