"""
Question 45: Triangular, Pentagonal, and Hexagonal
URL: https://projecteuler.net/problem=45

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle:     T_n = n(n + 1)/2    1, 3, 6, 10, 15, ...
Pentagonal:   P_n = n(3n - 1)/2   1, 5, 12, 22, 35, ...
Hexagonal:    H_n = n(2n - 1)     1, 6, 15, 28, 45, ...

It can be verified that T_285 = P_165 = H_143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

Measured Runtime: ~0.00700s
"""

import time


def is_pentagonal(n: int) -> bool:
    """Checks if a number is pentagonal."""
    if n <= 0:
        return False
    val = (1 + 24 * n) ** 0.5
    return val.is_integer() and (val + 1) % 6 == 0


def solve() -> int:
    """Finds the next triangle number (after 40755) that is also pentagonal and hexagonal."""
    m = 144
    while True:
        h = m * (2 * m - 1)
        if is_pentagonal(h):
            return h
        m += 1


if __name__ == "__main__":
    start_time = time.perf_counter()
    answer = solve()
    elapsed = time.perf_counter() - start_time

    print(f"Answer: {answer}")
    print(f"Execution Time: {elapsed:.6f} seconds")
